//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexio.Bat.Emi.VisuV4.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexio.Bat.Emi.VisuV4.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not load .
        /// </summary>
        public static string CanNotLoad {
            get {
                return ResourceManager.GetString("CanNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not load {0}, function {1}.
        /// </summary>
        public static string CanNotLoad0Function1 {
            get {
                return ResourceManager.GetString("CanNotLoad0Function1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can not save the test, risk to delete files.
        /// </summary>
        public static string CanNotSaveTheTestRiskToDeleteFiles {
            get {
                return ResourceManager.GetString("CanNotSaveTheTestRiskToDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error Init Function : {0}.
        /// </summary>
        public static string ErrorInitFunction0 {
            get {
                return ResourceManager.GetString("ErrorInitFunction0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fast.
        /// </summary>
        public static string eSpeed_Speed_fast {
            get {
                return ResourceManager.GetString("eSpeed_Speed_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medium.
        /// </summary>
        public static string eSpeed_Speed_medium {
            get {
                return ResourceManager.GetString("eSpeed_Speed_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slow.
        /// </summary>
        public static string eSpeed_Speed_slow {
            get {
                return ResourceManager.GetString("eSpeed_Speed_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very Fast.
        /// </summary>
        public static string eSpeed_Speed_very_fast {
            get {
                return ResourceManager.GetString("eSpeed_Speed_very_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very Slow.
        /// </summary>
        public static string eSpeed_Speed_very_slow {
            get {
                return ResourceManager.GetString("eSpeed_Speed_very_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute Function : {0}.
        /// </summary>
        public static string ExecuteFunction0 {
            get {
                return ResourceManager.GetString("ExecuteFunction0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Init Function : {0}.
        /// </summary>
        public static string InitFunction0 {
            get {
                return ResourceManager.GetString("InitFunction0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IL Factor.
        /// </summary>
        public static string SpecialFilter_CRBM_IL {
            get {
                return ResourceManager.GetString("SpecialFilter_CRBM_IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Measurement.
        /// </summary>
        public static string SpecialFilter_CRBM_Prec {
            get {
                return ResourceManager.GetString("SpecialFilter_CRBM_Prec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Axis.
        /// </summary>
        public static string SpecialFilter_GTEM_Axis {
            get {
                return ResourceManager.GetString("SpecialFilter_GTEM_Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Correlation.
        /// </summary>
        public static string SpecialFilter_GTEM_Correlation {
            get {
                return ResourceManager.GetString("SpecialFilter_GTEM_Correlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Broadband.
        /// </summary>
        public static string SpecialFilter_Mil_BB {
            get {
                return ResourceManager.GetString("SpecialFilter_Mil_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Narrowband.
        /// </summary>
        public static string SpecialFilter_Mil_NB {
            get {
                return ResourceManager.GetString("SpecialFilter_Mil_NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not Defined.
        /// </summary>
        public static string SpecialFilter_Mil_ND {
            get {
                return ResourceManager.GetString("SpecialFilter_Mil_ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string SpecialFilter_None {
            get {
                return ResourceManager.GetString("SpecialFilter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyzer.
        /// </summary>
        public static string TypesProgression_PROG_AUCUNE {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_AUCUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FFT.
        /// </summary>
        public static string TypesProgression_PROG_ESU_FFT {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_ESU_FFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à FFT with Data Reduction.
        /// </summary>
        public static string TypesProgression_PROG_ESU_FFT_DATA_REDUCTION {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_ESU_FFT_DATA_REDUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linear scan.
        /// </summary>
        public static string TypesProgression_PROG_LINEAIRE {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_LINEAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyzer Log.
        /// </summary>
        public static string TypesProgression_PROG_LOG {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log (%) scan.
        /// </summary>
        public static string TypesProgression_PROG_POURCENTAGE {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_POURCENTAGE", resourceCulture);
            }
        }
    }
}
