//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexio.Bat.Emi.VisuV4.Definition.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexio.Bat.Emi.VisuV4.Definition.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new style.
        /// </summary>
        internal static string AddNewStyle {
            get {
                return ResourceManager.GetString("AddNewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Applied style.
        /// </summary>
        internal static string AppliedStyle {
            get {
                return ResourceManager.GetString("AppliedStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure to delete the cache ?.
        /// </summary>
        internal static string AreYouSureToDeleteTheCache {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteTheCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one combination Column/Position covers this Source&apos;s combination.
        /// </summary>
        internal static string AtLeastOneCombinationColumnPositionCoversThisSourceSCombination {
            get {
                return ResourceManager.GetString("AtLeastOneCombinationColumnPositionCoversThisSourceSCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At least one combination Project/Position covers this Source&apos;s combination.
        /// </summary>
        internal static string AtLeastOneCombinationProjectPositionCoversThisSourceSCombination {
            get {
                return ResourceManager.GetString("AtLeastOneCombinationProjectPositionCoversThisSourceSCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear cache.
        /// </summary>
        internal static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Column.
        /// </summary>
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration directory:.
        /// </summary>
        internal static string ConfigurationDirectory {
            get {
                return ResourceManager.GetString("ConfigurationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete cache.
        /// </summary>
        internal static string DeleteCache {
            get {
                return ResourceManager.GetString("DeleteCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detector.
        /// </summary>
        internal static string Detector {
            get {
                return ResourceManager.GetString("Detector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directory not found.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EMI Override.
        /// </summary>
        internal static string EMIOverride {
            get {
                return ResourceManager.GetString("EMIOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à EMI Override&apos;s default save directory is not accessible. Do you want to save this configuration somewhere else ?.
        /// </summary>
        internal static string EMIOverrideSDefaultSaveDirectoryIsNotAccessible {
            get {
                return ResourceManager.GetString("EMIOverrideSDefaultSaveDirectoryIsNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Complete.
        /// </summary>
        internal static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Imported From File.
        /// </summary>
        internal static string ImportedFromFile {
            get {
                return ResourceManager.GetString("ImportedFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is Visible.
        /// </summary>
        internal static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock Color.
        /// </summary>
        internal static string LockColor {
            get {
                return ResourceManager.GetString("LockColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock Size.
        /// </summary>
        internal static string LockSize {
            get {
                return ResourceManager.GetString("LockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lock Visibility.
        /// </summary>
        internal static string LockVisibility {
            get {
                return ResourceManager.GetString("LockVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No name for this curve.
        /// </summary>
        internal static string NoNameForThisCurve {
            get {
                return ResourceManager.GetString("NoNameForThisCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old Project (V3) or Max.
        /// </summary>
        internal static string OldProjectV3OrMax {
            get {
                return ResourceManager.GetString("OldProjectV3OrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more style cover all columns for this source.
        /// </summary>
        internal static string OneOrMoreStyleCoverAllColumnsForThisSource {
            get {
                return ResourceManager.GetString("OneOrMoreStyleCoverAllColumnsForThisSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more style cover all positions for this Curve.
        /// </summary>
        internal static string OneOrMoreStyleCoverAllPositionsForThisCurve {
            get {
                return ResourceManager.GetString("OneOrMoreStyleCoverAllPositionsForThisCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more style cover all positions for this detector.
        /// </summary>
        internal static string OneOrMoreStyleCoverAllPositionsForThisDetector {
            get {
                return ResourceManager.GetString("OneOrMoreStyleCoverAllPositionsForThisDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more style cover all positions for this source.
        /// </summary>
        internal static string OneOrMoreStyleCoverAllPositionsForThisSource {
            get {
                return ResourceManager.GetString("OneOrMoreStyleCoverAllPositionsForThisSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more style cover all projects for this detector.
        /// </summary>
        internal static string OneOrMoreStyleCoverAllProjectsForThisDetector {
            get {
                return ResourceManager.GetString("OneOrMoreStyleCoverAllProjectsForThisDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more style cover have the same position for this detector.
        /// </summary>
        internal static string OneOrMoreStyleCoverHaveTheSamePositionForThisDetector {
            get {
                return ResourceManager.GetString("OneOrMoreStyleCoverHaveTheSamePositionForThisDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One or more style cover have the same project for this detector.
        /// </summary>
        internal static string OneOrMoreStyleCoverHaveTheSameProjectForThisDetector {
            get {
                return ResourceManager.GetString("OneOrMoreStyleCoverHaveTheSameProjectForThisDetector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Override Color.
        /// </summary>
        internal static string OverrideColor {
            get {
                return ResourceManager.GetString("OverrideColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Override Projection.
        /// </summary>
        internal static string OverrideProjection {
            get {
                return ResourceManager.GetString("OverrideProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Override Size.
        /// </summary>
        internal static string OverrideSize {
            get {
                return ResourceManager.GetString("OverrideSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projection.
        /// </summary>
        internal static string Projection {
            get {
                return ResourceManager.GetString("Projection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset values in combobox with a default list. (Use it if you have too many values in a combobox).
        /// </summary>
        internal static string ResetValuesInComboboxWithADefaultListUseItIfYouHaveTooManyValuesInACombobox {
            get {
                return ResourceManager.GetString("ResetValuesInComboboxWithADefaultListUseItIfYouHaveTooManyValuesInACombobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select EMI Override configuration to import.
        /// </summary>
        internal static string SelectEMIOverrideConfigurationToImport {
            get {
                return ResourceManager.GetString("SelectEMIOverrideConfigurationToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Styles export complete.
        /// </summary>
        internal static string StylesExportComplete {
            get {
                return ResourceManager.GetString("StylesExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Combination Project/Name/Position is already defined.
        /// </summary>
        internal static string ThisCombinationProjectNamePositionIsAlreadyDefined {
            get {
                return ResourceManager.GetString("ThisCombinationProjectNamePositionIsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This Combination Source/Column/Position is already defined.
        /// </summary>
        internal static string ThisCombinationSourceColumnPositionIsAlreadyDefined {
            get {
                return ResourceManager.GetString("ThisCombinationSourceColumnPositionIsAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to locate EMI Override&apos;s file&apos;s directory. Please check your configuration. The editor will use the default settings..
        /// </summary>
        internal static string UnableToLocateEMIOverrideSFileSDirectory {
            get {
                return ResourceManager.GetString("UnableToLocateEMIOverrideSFileSDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visibility.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your combination Column/Source is already covered.
        /// </summary>
        internal static string YourCombinationColumnSourceIsAlreadyCovered {
            get {
                return ResourceManager.GetString("YourCombinationColumnSourceIsAlreadyCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your combination Position/Source is already covered.
        /// </summary>
        internal static string YourCombinationPositionSourceIsAlreadyCovered {
            get {
                return ResourceManager.GetString("YourCombinationPositionSourceIsAlreadyCovered", resourceCulture);
            }
        }
    }
}
