//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexioMax3.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexioMax3.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load .
        /// </summary>
        public static string CanNotLoad {
            get {
                return ResourceManager.GetString("CanNotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load {0}, function {1}.
        /// </summary>
        public static string CanNotLoad0Function1 {
            get {
                return ResourceManager.GetString("CanNotLoad0Function1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save the test, risk to delete files.
        /// </summary>
        public static string CanNotSaveTheTestRiskToDeleteFiles {
            get {
                return ResourceManager.GetString("CanNotSaveTheTestRiskToDeleteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Init Function : {0}.
        /// </summary>
        public static string ErrorInitFunction0 {
            get {
                return ResourceManager.GetString("ErrorInitFunction0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string eSpeed_Speed_fast {
            get {
                return ResourceManager.GetString("eSpeed_Speed_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string eSpeed_Speed_medium {
            get {
                return ResourceManager.GetString("eSpeed_Speed_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string eSpeed_Speed_slow {
            get {
                return ResourceManager.GetString("eSpeed_Speed_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Fast.
        /// </summary>
        public static string eSpeed_Speed_very_fast {
            get {
                return ResourceManager.GetString("eSpeed_Speed_very_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Slow.
        /// </summary>
        public static string eSpeed_Speed_very_slow {
            get {
                return ResourceManager.GetString("eSpeed_Speed_very_slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Function : {0}.
        /// </summary>
        public static string ExecuteFunction0 {
            get {
                return ResourceManager.GetString("ExecuteFunction0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init Function : {0}.
        /// </summary>
        public static string InitFunction0 {
            get {
                return ResourceManager.GetString("InitFunction0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL Factor.
        /// </summary>
        public static string SpecialFilter_CRBM_IL {
            get {
                return ResourceManager.GetString("SpecialFilter_CRBM_IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string SpecialFilter_CRBM_Prec {
            get {
                return ResourceManager.GetString("SpecialFilter_CRBM_Prec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        public static string SpecialFilter_GTEM_Axis {
            get {
                return ResourceManager.GetString("SpecialFilter_GTEM_Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation.
        /// </summary>
        public static string SpecialFilter_GTEM_Correlation {
            get {
                return ResourceManager.GetString("SpecialFilter_GTEM_Correlation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadband.
        /// </summary>
        public static string SpecialFilter_Mil_BB {
            get {
                return ResourceManager.GetString("SpecialFilter_Mil_BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrowband.
        /// </summary>
        public static string SpecialFilter_Mil_NB {
            get {
                return ResourceManager.GetString("SpecialFilter_Mil_NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Defined.
        /// </summary>
        public static string SpecialFilter_Mil_ND {
            get {
                return ResourceManager.GetString("SpecialFilter_Mil_ND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SpecialFilter_None {
            get {
                return ResourceManager.GetString("SpecialFilter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer.
        /// </summary>
        public static string TypesProgression_PROG_AUCUNE {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_AUCUNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        public static string TypesProgression_PROG_ESU_FFT {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_ESU_FFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT with Data Reduction.
        /// </summary>
        public static string TypesProgression_PROG_ESU_FFT_DATA_REDUCTION {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_ESU_FFT_DATA_REDUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear scan.
        /// </summary>
        public static string TypesProgression_PROG_LINEAIRE {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_LINEAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzer Log.
        /// </summary>
        public static string TypesProgression_PROG_LOG {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log (%) scan.
        /// </summary>
        public static string TypesProgression_PROG_POURCENTAGE {
            get {
                return ResourceManager.GetString("TypesProgression_PROG_POURCENTAGE", resourceCulture);
            }
        }
    }
}
